export const navColorStyles = {
    '--SideNav-background': 'var(--mui-palette-neutral-900)',
    '--SideNav-color': 'var(--mui-palette-common-white)',
    '--SideNav-border': '1px solid var(--mui-palette-neutral-700)',
    '--NavGroup-title-color': 'var(--mui-palette-neutral-400)',
    '--NavItem-color': 'var(--mui-palette-neutral-300)',
    '--NavItem-hover-background': 'var(--mui-palette-action-hover)',
    '--NavItem-active-background': 'var(--mui-palette-primary-main)',
    '--NavItem-active-color': 'var(--mui-palette-primary-contrastText)',
    '--NavItem-disabled-color': 'var(--mui-palette-neutral-500)',
    '--NavItem-icon-color': 'var(--mui-palette-neutral-400)',
    '--NavItem-icon-active-color': 'var(--mui-palette-primary-contrastText)',
    '--NavItem-icon-disabled-color': 'var(--mui-palette-neutral-600)',
    '--NavItem-expand-color': 'var(--mui-palette-neutral-400)',
    '--NavItem-children-border': 'var(--mui-palette-neutral-700)',
    '--NavItem-children-indicator': 'var(--mui-palette-neutral-400)',
    '--Workspaces-background': 'var(--mui-palette-neutral-950)',
    '--Workspaces-border-color': 'var(--mui-palette-neutral-700)',
    '--Workspaces-title-color': 'var(--mui-palette-neutral-400)',
    '--Workspaces-name-color': 'var(--mui-palette-neutral-300)',
    '--Workspaces-expand-color': 'var(--mui-palette-neutral-400)'
}